### PR TITLE
Fix path translation. Remove rand dependency.

### LINKED ISSUE #16: Remove rand dependency
The rand dependency only actually ends up in non-windows, non-mac, non-linux builds, but I think it could probably be removed entirely.  A simple (but inconvenient) method would be to use `libc::rand` since that dependency isn't going anywhere.

### PR DESCRIPTION
**Pull request by calebzulawski**
On some (most?) POSIX platforms, `shm_open` does path translation (for example, `/foo` might open `/tmp/foo`).  On some BSDs, for example, this path must only have a leading slash and no other slashes, so this change makes the path more universally supported.

To remove `rand`, I repeatedly count from 0 to 9999999 and use that (formatted to a string) as the path suffix.  This is probably worse if lots of contention occurs, but I'm guessing about the same or faster if there is no contention.

Closes #16.

### CODE REVIEW

File: src/os/unix/posix/memfd.rs [hunk 1]
```diff
@@ -32,31 +32,26 @@ pub fn memfd_open() -> Result<c_int> {
...
-    let end = path.len() - 1;
-
-    loop {
-        for dst in &mut path[10..end] {
-            *dst = rng.sample(&Alphanumeric) as u8;
-        }
+    for i in (0..10000000).cycle() {
+        let path = {
+            use std::io::Write;
+            write!(&mut path_bytes[6..], "{:0>7}", i).unwrap();
```
Comment (kalamay) [inline src/os/unix/posix/memfd.rs]: What if instead of an iterative cycle, we try for a less deterministic value? One thought could be to use something approximately time-based with an integer mix, for example:

```rust
fn id() -> u32 {
    let mut t = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .subsec_nanos();
    
    // Mix using Jenkins' integer hash
    t = t.wrapping_add(0x7ed55d16).wrapping_add(t << 12);
    t = (t ^ 0xc761c23c) ^ (t >> 19);
    t = t.wrapping_add(0x165667b1).wrapping_add(t << 5);
    t = t.wrapping_add(0xd3a2646c) ^ (t << 9);
    t = t.wrapping_add(0xfd7046c5).wrapping_add(t << 3);
    t = (t ^ 0xb55a4f09) ^ (t >> 16);
    t
}
```

And then we could do:

```rust
write!(&mut path_bytes[6..], "{:0>7}", id()).unwrap();
```

**Comment by kalamay** [comment]
Sorry for the delay, I've been moving, but overall I think this looks great! I'm a little hesitant to go for a direct iterative approach as it would be progressively more contentious with each actively mapped value. Again, thanks for the contribution!

File: src/os/unix/posix/memfd.rs (hunk 1 above)
Comment (calebzulawski) [reply src/os/unix/posix/memfd.rs]: Hmm... using the time works but I'm not sure using the hash is necessary.  The output space will have the same number of unique values (1e9) right?

Comment (kalamay) [reply src/os/unix/posix/memfd.rs]: Yeah the output space would have exact the same number of unique values, but they would't be sequential. Though, really, that may not actually provide much utility here.

Comment (calebzulawski) [reply src/os/unix/posix/memfd.rs]: I was hoping to avoid the extra syscall, but this is probably way to go.  Updated it to use the time directly.

**Comment by calebzulawski** [comment]
No problem, I've been busy with some other things too.  I just updated it with improved contention behavior.  By the way, I ended up needing a `no_std` variant of this algorithm and published [`shm_open_anonymous`](https://crates.io/crates/shm_open_anonymous) if you ever find it useful.

File: src/os/unix/posix/memfd.rs (hunk 1 above)
Comment (kalamay) [reply src/os/unix/posix/memfd.rs]: Yeah, totally do get that. I was thinking the trade-off between checking the time would be preferable to the syscall for attempting to create a path that already exists. With several running at the same time, I think there would be fewer overall calls due to the distribution of names.

**Review by kalamay — APPROVED** [review]

**Comment by kalamay** [comment]
Oh nice! I'm going to check that out!
